using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{
    public class vwInpatient
    {
        public int ID { get; set; }
        public string EnterpriseName { get; set; }
        public string EnterpriseID { get; set; }
        public string ExportQueueKey { get; set; }
        public string EventTypeKey { get; set; }
        public string RecordType { get; set; }
        public string CodeSetKey { get; set; }
        public string VisitKey { get; set; }
        public string FacilityName { get; set; }
        public string WorkingOrFinal { get; set; }
        public string PatientClassifications3M { get; set; }
        public string PatientType { get; set; }
        public string PatientTypeDescription { get; set; }
        public string VisitType { get; set; }
        public string VisitTypeDescription { get; set; }
        public string PatientLastName { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientMiddleName { get; set; }
        public string PatientAlias { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BirthDateTime { get; set; }
        public string BirthWeight { get; set; }
        public string Sex { get; set; }
        public string MaritalStatus { get; set; }
        public string Race { get; set; }
        public string RaceDescription { get; set; }
        public string Ethnicity { get; set; }
        public string EthnicityDescription { get; set; }
        public string SSN { get; set; }
        public string CitizenshipStatus { get; set; }
        public string MilitaryStatus { get; set; }
        public string DriversLicenseNumber { get; set; }
        public string ProviderId { get; set; }
        public string ProviderNumber { get; set; }
        public string PatientId { get; set; }
        public string MRN { get; set; }
        public string ClaimID { get; set; }
        public string AdmitDate { get; set; }
        public string AdmitHour { get; set; }
        public string TypeOfAdmission { get; set; }
        public string AdmissionTypeDescription { get; set; }
        public string MarylandNatureOfAdmission { get; set; }
        public string MarylandNatureOfAdmissionDescription { get; set; }
        public string PointOfOrigin { get; set; }
        public string AgeInDays { get; set; }
        public string AgeInYears { get; set; }
        public string IcdVersionQualifier { get; set; }
        public string AdmitDiagnosis { get; set; }
        public string PrincipalDiagnosis { get; set; }
        public string PrincipalDiagnosisPOA { get; set; }
        public string PrincipalProcedure { get; set; }
        public string PrincipalProcedureDate { get; set; }
        public string LOS { get; set; }
        public string DischargeDate { get; set; }
        public string DischargeHour { get; set; }
        public string DischargeStatus { get; set; }
        public string DischargeStatusLocal { get; set; }
        public string PrimaryPayer { get; set; }
        public string SecondaryPayer { get; set; }
        public string TertiaryPayer { get; set; }
        public string FinancialClass { get; set; }
        public string Coder { get; set; }
        public string Reviewer { get; set; }
        public string NursingUnit { get; set; }
        public string PatientRoom { get; set; }
        public string PatientBed { get; set; }
        public string AttendingNPI { get; set; }
        public string AttendingName { get; set; }
        public string AttendingDepartment { get; set; }
        public string OperatingNPI { get; set; }
        public string OperatingName { get; set; }
        public string OperatingDepartment { get; set; }
        public string OthOperatingNPI { get; set; }
        public string OthOperatingName { get; set; }
        public string OthOperatingDepartment { get; set; }
        public string RenderingNPI { get; set; }
        public string RenderingName { get; set; }
        public string RenderingDepartment { get; set; }
        public string GrouperType { get; set; }
        public string GrouperVersion { get; set; }
        public string PaymentDRG { get; set; }
        public string PaymentSOI { get; set; }
        public string TotalCharges { get; set; }
        public string TotalNonCharges { get; set; }
        public string TypeOfBill { get; set; }
        public string PreviousDischargeDate { get; set; }
        public string BrainInjuryReserveFlag { get; set; }
        public string CancerReserveFlag { get; set; }
        public string TypeOfService { get; set; }
        public string DeathDate { get; set; }
        public string ConditionCode1 { get; set; }
        public string ConditionCode2 { get; set; }
        public string ConditionCode3 { get; set; }
        public string ConditionCode4 { get; set; }
        public string ConditionCode5 { get; set; }
        public string ConditionCode6 { get; set; }
        public string ConditionCode7 { get; set; }
        public string ConditionCode8 { get; set; }
        public string ConditionCode9 { get; set; }
        public string ConditionCode10 { get; set; }
        public string ConditionCode11 { get; set; }
        public string OccurrenceSpanCode1 { get; set; }
        public string OccurrenceSpanCodeFromDate1 { get; set; }
        public string OccurrenceSpanCodeThroughDate1 { get; set; }
        public string OccurrenceSpanCode2 { get; set; }
        public string OccurrenceSpanCodeFromDate2 { get; set; }
        public string OccurrenceSpanCodeThroughDate2 { get; set; }
        public string OccurrenceSpanCode3 { get; set; }
        public string OccurrenceSpanCodeFromDate3 { get; set; }
        public string OccurrenceSpanCodeThroughDate3 { get; set; }
        public string OccurrenceSpanCode4 { get; set; }
        public string OccurrenceSpanCodeFromDate4 { get; set; }
        public string OccurrenceSpanCodeThroughDate4 { get; set; }
        public string OccurrenceSpanCode5 { get; set; }
        public string OccurrenceSpanCodeFromDate5 { get; set; }
        public string OccurrenceSpanCodeThroughDate5 { get; set; }
        public string ValueCode1 { get; set; }
        public string ValueCodeAmount1 { get; set; }
        public string ValueCode2 { get; set; }
        public string ValueCodeAmount2 { get; set; }
        public string ValueCode3 { get; set; }
        public string ValueCodeAmount3 { get; set; }
        public string ValueCode4 { get; set; }
        public string ValueCodeAmount4 { get; set; }
        public string ValueCode5 { get; set; }
        public string ValueCodeAmount5 { get; set; }
        public string ValueCode6 { get; set; }
        public string ValueCodeAmount6 { get; set; }
        public string ValueCode7 { get; set; }
        public string ValueCodeAmount7 { get; set; }
        public string ValueCode8 { get; set; }
        public string ValueCodeAmount8 { get; set; }
        public string ValueCode9 { get; set; }
        public string ValueCodeAmount9 { get; set; }
        public string ValueCode10 { get; set; }
        public string ValueCodeAmount10 { get; set; }
        public string ValueCode11 { get; set; }
        public string ValueCodeAmount11 { get; set; }
        public string ValueCode12 { get; set; }
        public string ValueCodeAmount12 { get; set; }
        public string SecondaryDiagnosis1 { get; set; }
        public string SecondaryDiagnosisPOA1 { get; set; }
        public string SecondaryDiagnosis2 { get; set; }
        public string SecondaryDiagnosisPOA2 { get; set; }
        public string SecondaryDiagnosis3 { get; set; }
        public string SecondaryDiagnosisPOA3 { get; set; }
        public string SecondaryDiagnosis4 { get; set; }
        public string SecondaryDiagnosisPOA4 { get; set; }
        public string SecondaryDiagnosis5 { get; set; }
        public string SecondaryDiagnosisPOA5 { get; set; }
        public string SecondaryDiagnosis6 { get; set; }
        public string SecondaryDiagnosisPOA6 { get; set; }
        public string SecondaryDiagnosis7 { get; set; }
        public string SecondaryDiagnosisPOA7 { get; set; }
        public string SecondaryDiagnosis8 { get; set; }
        public string SecondaryDiagnosisPOA8 { get; set; }
        public string SecondaryDiagnosis9 { get; set; }
        public string SecondaryDiagnosisPOA9 { get; set; }
        public string SecondaryDiagnosis10 { get; set; }
        public string SecondaryDiagnosisPOA10 { get; set; }
        public string SecondaryDiagnosis11 { get; set; }
        public string SecondaryDiagnosisPOA11 { get; set; }
        public string SecondaryDiagnosis12 { get; set; }
        public string SecondaryDiagnosisPOA12 { get; set; }
        public string SecondaryDiagnosis13 { get; set; }
        public string SecondaryDiagnosisPOA13 { get; set; }
        public string SecondaryDiagnosis14 { get; set; }
        public string SecondaryDiagnosisPOA14 { get; set; }
        public string SecondaryDiagnosis15 { get; set; }
        public string SecondaryDiagnosisPOA15 { get; set; }
        public string SecondaryDiagnosis16 { get; set; }
        public string SecondaryDiagnosisPOA16 { get; set; }
        public string SecondaryDiagnosis17 { get; set; }
        public string SecondaryDiagnosisPOA17 { get; set; }
        public string SecondaryDiagnosis18 { get; set; }
        public string SecondaryDiagnosisPOA18 { get; set; }
        public string SecondaryDiagnosis19 { get; set; }
        public string SecondaryDiagnosisPOA19 { get; set; }
        public string SecondaryDiagnosis20 { get; set; }
        public string SecondaryDiagnosisPOA20 { get; set; }
        public string SecondaryDiagnosis21 { get; set; }
        public string SecondaryDiagnosisPOA21 { get; set; }
        public string SecondaryDiagnosis22 { get; set; }
        public string SecondaryDiagnosisPOA22 { get; set; }
        public string SecondaryDiagnosis23 { get; set; }
        public string SecondaryDiagnosisPOA23 { get; set; }
        public string SecondaryDiagnosis24 { get; set; }
        public string SecondaryDiagnosisPOA24 { get; set; }
        public string SecondaryDiagnosis25 { get; set; }
        public string SecondaryDiagnosisPOA25 { get; set; }
        public string SecondaryDiagnosis26 { get; set; }
        public string SecondaryDiagnosisPOA26 { get; set; }
        public string SecondaryDiagnosis27 { get; set; }
        public string SecondaryDiagnosisPOA27 { get; set; }
        public string SecondaryDiagnosis28 { get; set; }
        public string SecondaryDiagnosisPOA28 { get; set; }
        public string SecondaryDiagnosis29 { get; set; }
        public string SecondaryDiagnosisPOA29 { get; set; }
        public string SecondaryDiagnosis30 { get; set; }
        public string SecondaryDiagnosisPOA30 { get; set; }
        public string SecondaryDiagnosis31 { get; set; }
        public string SecondaryDiagnosisPOA31 { get; set; }
        public string SecondaryDiagnosis32 { get; set; }
        public string SecondaryDiagnosisPOA32 { get; set; }
        public string SecondaryDiagnosis33 { get; set; }
        public string SecondaryDiagnosisPOA33 { get; set; }
        public string SecondaryDiagnosis34 { get; set; }
        public string SecondaryDiagnosisPOA34 { get; set; }
        public string SecondaryDiagnosis35 { get; set; }
        public string SecondaryDiagnosisPOA35 { get; set; }
        public string SecondaryDiagnosis36 { get; set; }
        public string SecondaryDiagnosisPOA36 { get; set; }
        public string SecondaryDiagnosis37 { get; set; }
        public string SecondaryDiagnosisPOA37 { get; set; }
        public string SecondaryDiagnosis38 { get; set; }
        public string SecondaryDiagnosisPOA38 { get; set; }
        public string SecondaryDiagnosis39 { get; set; }
        public string SecondaryDiagnosisPOA39 { get; set; }
        public string SecondaryDiagnosis40 { get; set; }
        public string SecondaryDiagnosisPOA40 { get; set; }
        public string SecondaryDiagnosis41 { get; set; }
        public string SecondaryDiagnosisPOA41 { get; set; }
        public string SecondaryDiagnosis42 { get; set; }
        public string SecondaryDiagnosisPOA42 { get; set; }
        public string SecondaryDiagnosis43 { get; set; }
        public string SecondaryDiagnosisPOA43 { get; set; }
        public string SecondaryDiagnosis44 { get; set; }
        public string SecondaryDiagnosisPOA44 { get; set; }
        public string SecondaryDiagnosis45 { get; set; }
        public string SecondaryDiagnosisPOA45 { get; set; }
        public string SecondaryDiagnosis46 { get; set; }
        public string SecondaryDiagnosisPOA46 { get; set; }
        public string SecondaryDiagnosis47 { get; set; }
        public string SecondaryDiagnosisPOA47 { get; set; }
        public string SecondaryDiagnosis48 { get; set; }
        public string SecondaryDiagnosisPOA48 { get; set; }
        public string SecondaryDiagnosis49 { get; set; }
        public string SecondaryDiagnosisPOA49 { get; set; }
        public string SecondaryDiagnosis50 { get; set; }
        public string SecondaryDiagnosisPOA50 { get; set; }
        public string SecondaryDiagnosis51 { get; set; }
        public string SecondaryDiagnosisPOA51 { get; set; }
        public string SecondaryDiagnosis52 { get; set; }
        public string SecondaryDiagnosisPOA52 { get; set; }
        public string SecondaryDiagnosis53 { get; set; }
        public string SecondaryDiagnosisPOA53 { get; set; }
        public string SecondaryDiagnosis54 { get; set; }
        public string SecondaryDiagnosisPOA54 { get; set; }
        public string SecondaryDiagnosis55 { get; set; }
        public string SecondaryDiagnosisPOA55 { get; set; }
        public string SecondaryDiagnosis56 { get; set; }
        public string SecondaryDiagnosisPOA56 { get; set; }
        public string SecondaryDiagnosis57 { get; set; }
        public string SecondaryDiagnosisPOA57 { get; set; }
        public string SecondaryDiagnosis58 { get; set; }
        public string SecondaryDiagnosisPOA58 { get; set; }
        public string SecondaryDiagnosis59 { get; set; }
        public string SecondaryDiagnosisPOA59 { get; set; }
        public string SecondaryDiagnosis60 { get; set; }
        public string SecondaryDiagnosisPOA60 { get; set; }
        public string SecondaryDiagnosis61 { get; set; }
        public string SecondaryDiagnosisPOA61 { get; set; }
        public string SecondaryDiagnosis62 { get; set; }
        public string SecondaryDiagnosisPOA62 { get; set; }
        public string SecondaryDiagnosis63 { get; set; }
        public string SecondaryDiagnosisPOA63 { get; set; }
        public string SecondaryDiagnosis64 { get; set; }
        public string SecondaryDiagnosisPOA64 { get; set; }
        public string SecondaryDiagnosis65 { get; set; }
        public string SecondaryDiagnosisPOA65 { get; set; }
        public string SecondaryDiagnosis66 { get; set; }
        public string SecondaryDiagnosisPOA66 { get; set; }
        public string SecondaryDiagnosis67 { get; set; }
        public string SecondaryDiagnosisPOA67 { get; set; }
        public string SecondaryDiagnosis68 { get; set; }
        public string SecondaryDiagnosisPOA68 { get; set; }
        public string SecondaryDiagnosis69 { get; set; }
        public string SecondaryDiagnosisPOA69 { get; set; }
        public string SecondaryDiagnosis70 { get; set; }
        public string SecondaryDiagnosisPOA70 { get; set; }
        public string SecondaryDiagnosis71 { get; set; }
        public string SecondaryDiagnosisPOA71 { get; set; }
        public string SecondaryDiagnosis72 { get; set; }
        public string SecondaryDiagnosisPOA72 { get; set; }
        public string SecondaryDiagnosis73 { get; set; }
        public string SecondaryDiagnosisPOA73 { get; set; }
        public string SecondaryDiagnosis74 { get; set; }
        public string SecondaryDiagnosisPOA74 { get; set; }
        public string SecondaryDiagnosis75 { get; set; }
        public string SecondaryDiagnosisPOA75 { get; set; }
        public string SecondaryDiagnosis76 { get; set; }
        public string SecondaryDiagnosisPOA76 { get; set; }
        public string SecondaryDiagnosis77 { get; set; }
        public string SecondaryDiagnosisPOA77 { get; set; }
        public string SecondaryDiagnosis78 { get; set; }
        public string SecondaryDiagnosisPOA78 { get; set; }
        public string SecondaryDiagnosis79 { get; set; }
        public string SecondaryDiagnosisPOA79 { get; set; }
        public string SecondaryDiagnosis80 { get; set; }
        public string SecondaryDiagnosisPOA80 { get; set; }
        public string SecondaryDiagnosis81 { get; set; }
        public string SecondaryDiagnosisPOA81 { get; set; }
        public string SecondaryDiagnosis82 { get; set; }
        public string SecondaryDiagnosisPOA82 { get; set; }
        public string SecondaryDiagnosis83 { get; set; }
        public string SecondaryDiagnosisPOA83 { get; set; }
        public string SecondaryDiagnosis84 { get; set; }
        public string SecondaryDiagnosisPOA84 { get; set; }
        public string SecondaryDiagnosis85 { get; set; }
        public string SecondaryDiagnosisPOA85 { get; set; }
        public string SecondaryDiagnosis86 { get; set; }
        public string SecondaryDiagnosisPOA86 { get; set; }
        public string SecondaryDiagnosis87 { get; set; }
        public string SecondaryDiagnosisPOA87 { get; set; }
        public string SecondaryDiagnosis88 { get; set; }
        public string SecondaryDiagnosisPOA88 { get; set; }
        public string SecondaryDiagnosis89 { get; set; }
        public string SecondaryDiagnosisPOA89 { get; set; }
        public string SecondaryDiagnosis90 { get; set; }
        public string SecondaryDiagnosisPOA90 { get; set; }
        public string SecondaryDiagnosis91 { get; set; }
        public string SecondaryDiagnosisPOA91 { get; set; }
        public string SecondaryDiagnosis92 { get; set; }
        public string SecondaryDiagnosisPOA92 { get; set; }
        public string SecondaryDiagnosis93 { get; set; }
        public string SecondaryDiagnosisPOA93 { get; set; }
        public string SecondaryDiagnosis94 { get; set; }
        public string SecondaryDiagnosisPOA94 { get; set; }
        public string SecondaryDiagnosis95 { get; set; }
        public string SecondaryDiagnosisPOA95 { get; set; }
        public string SecondaryDiagnosis96 { get; set; }
        public string SecondaryDiagnosisPOA96 { get; set; }
        public string SecondaryDiagnosis97 { get; set; }
        public string SecondaryDiagnosisPOA97 { get; set; }
        public string SecondaryDiagnosis98 { get; set; }
        public string SecondaryDiagnosisPOA98 { get; set; }
        public string SecondaryDiagnosis99 { get; set; }
        public string SecondaryDiagnosisPOA99 { get; set; }
        public string SecondaryProcedure1 { get; set; }
        public string SecondaryProcedureDate1 { get; set; }
        public string SecondaryProcedure2 { get; set; }
        public string SecondaryProcedureDate2 { get; set; }
        public string SecondaryProcedure3 { get; set; }
        public string SecondaryProcedureDate3 { get; set; }
        public string SecondaryProcedure4 { get; set; }
        public string SecondaryProcedureDate4 { get; set; }
        public string SecondaryProcedure5 { get; set; }
        public string SecondaryProcedureDate5 { get; set; }
        public string SecondaryProcedure6 { get; set; }
        public string SecondaryProcedureDate6 { get; set; }
        public string SecondaryProcedure7 { get; set; }
        public string SecondaryProcedureDate7 { get; set; }
        public string SecondaryProcedure8 { get; set; }
        public string SecondaryProcedureDate8 { get; set; }
        public string SecondaryProcedure9 { get; set; }
        public string SecondaryProcedureDate9 { get; set; }
        public string SecondaryProcedure10 { get; set; }
        public string SecondaryProcedureDate10 { get; set; }
        public string SecondaryProcedure11 { get; set; }
        public string SecondaryProcedureDate11 { get; set; }
        public string SecondaryProcedure12 { get; set; }
        public string SecondaryProcedureDate12 { get; set; }
        public string SecondaryProcedure13 { get; set; }
        public string SecondaryProcedureDate13 { get; set; }
        public string SecondaryProcedure14 { get; set; }
        public string SecondaryProcedureDate14 { get; set; }
        public string SecondaryProcedure15 { get; set; }
        public string SecondaryProcedureDate15 { get; set; }
        public string SecondaryProcedure16 { get; set; }
        public string SecondaryProcedureDate16 { get; set; }
        public string SecondaryProcedure17 { get; set; }
        public string SecondaryProcedureDate17 { get; set; }
        public string SecondaryProcedure18 { get; set; }
        public string SecondaryProcedureDate18 { get; set; }
        public string SecondaryProcedure19 { get; set; }
        public string SecondaryProcedureDate19 { get; set; }
        public string SecondaryProcedure20 { get; set; }
        public string SecondaryProcedureDate20 { get; set; }
        public string SecondaryProcedure21 { get; set; }
        public string SecondaryProcedureDate21 { get; set; }
        public string SecondaryProcedure22 { get; set; }
        public string SecondaryProcedureDate22 { get; set; }
        public string SecondaryProcedure23 { get; set; }
        public string SecondaryProcedureDate23 { get; set; }
        public string SecondaryProcedure24 { get; set; }
        public string SecondaryProcedureDate24 { get; set; }
        public string SecondaryProcedure25 { get; set; }
        public string SecondaryProcedureDate25 { get; set; }
        public string SecondaryProcedure26 { get; set; }
        public string SecondaryProcedureDate26 { get; set; }
        public string SecondaryProcedure27 { get; set; }
        public string SecondaryProcedureDate27 { get; set; }
        public string SecondaryProcedure28 { get; set; }
        public string SecondaryProcedureDate28 { get; set; }
        public string SecondaryProcedure29 { get; set; }
        public string SecondaryProcedureDate29 { get; set; }
        public string SecondaryProcedure30 { get; set; }
        public string SecondaryProcedureDate30 { get; set; }
        public string SecondaryProcedure31 { get; set; }
        public string SecondaryProcedureDate31 { get; set; }
        public string SecondaryProcedure32 { get; set; }
        public string SecondaryProcedureDate32 { get; set; }
        public string SecondaryProcedure33 { get; set; }
        public string SecondaryProcedureDate33 { get; set; }
        public string SecondaryProcedure34 { get; set; }
        public string SecondaryProcedureDate34 { get; set; }
        public string SecondaryProcedure35 { get; set; }
        public string SecondaryProcedureDate35 { get; set; }
        public string SecondaryProcedure36 { get; set; }
        public string SecondaryProcedureDate36 { get; set; }
        public string SecondaryProcedure37 { get; set; }
        public string SecondaryProcedureDate37 { get; set; }
        public string SecondaryProcedure38 { get; set; }
        public string SecondaryProcedureDate38 { get; set; }
        public string SecondaryProcedure39 { get; set; }
        public string SecondaryProcedureDate39 { get; set; }
        public string SecondaryProcedure40 { get; set; }
        public string SecondaryProcedureDate40 { get; set; }
        public string SecondaryProcedure41 { get; set; }
        public string SecondaryProcedureDate41 { get; set; }
        public string SecondaryProcedure42 { get; set; }
        public string SecondaryProcedureDate42 { get; set; }
        public string SecondaryProcedure43 { get; set; }
        public string SecondaryProcedureDate43 { get; set; }
        public string SecondaryProcedure44 { get; set; }
        public string SecondaryProcedureDate44 { get; set; }
        public string SecondaryProcedure45 { get; set; }
        public string SecondaryProcedureDate45 { get; set; }
        public string SecondaryProcedure46 { get; set; }
        public string SecondaryProcedureDate46 { get; set; }
        public string SecondaryProcedure47 { get; set; }
        public string SecondaryProcedureDate47 { get; set; }
        public string SecondaryProcedure48 { get; set; }
        public string SecondaryProcedureDate48 { get; set; }
        public string SecondaryProcedure49 { get; set; }
        public string SecondaryProcedureDate49 { get; set; }
        public string SecondaryProcedure50 { get; set; }
        public string SecondaryProcedureDate50 { get; set; }
        public string SecondaryProcedure51 { get; set; }
        public string SecondaryProcedureDate51 { get; set; }
        public string SecondaryProcedure52 { get; set; }
        public string SecondaryProcedureDate52 { get; set; }
        public string SecondaryProcedure53 { get; set; }
        public string SecondaryProcedureDate53 { get; set; }
        public string SecondaryProcedure54 { get; set; }
        public string SecondaryProcedureDate54 { get; set; }
        public string SecondaryProcedure55 { get; set; }
        public string SecondaryProcedureDate55 { get; set; }
        public string SecondaryProcedure56 { get; set; }
        public string SecondaryProcedureDate56 { get; set; }
        public string SecondaryProcedure57 { get; set; }
        public string SecondaryProcedureDate57 { get; set; }
        public string SecondaryProcedure58 { get; set; }
        public string SecondaryProcedureDate58 { get; set; }
        public string SecondaryProcedure59 { get; set; }
        public string SecondaryProcedureDate59 { get; set; }
        public string SecondaryProcedure60 { get; set; }
        public string SecondaryProcedureDate60 { get; set; }
        public string SecondaryProcedure61 { get; set; }
        public string SecondaryProcedureDate61 { get; set; }
        public string SecondaryProcedure62 { get; set; }
        public string SecondaryProcedureDate62 { get; set; }
        public string SecondaryProcedure63 { get; set; }
        public string SecondaryProcedureDate63 { get; set; }
        public string SecondaryProcedure64 { get; set; }
        public string SecondaryProcedureDate64 { get; set; }
        public string SecondaryProcedure65 { get; set; }
        public string SecondaryProcedureDate65 { get; set; }
        public string SecondaryProcedure66 { get; set; }
        public string SecondaryProcedureDate66 { get; set; }
        public string SecondaryProcedure67 { get; set; }
        public string SecondaryProcedureDate67 { get; set; }
        public string SecondaryProcedure68 { get; set; }
        public string SecondaryProcedureDate68 { get; set; }
        public string SecondaryProcedure69 { get; set; }
        public string SecondaryProcedureDate69 { get; set; }
        public string SecondaryProcedure70 { get; set; }
        public string SecondaryProcedureDate70 { get; set; }
        public string SecondaryProcedure71 { get; set; }
        public string SecondaryProcedureDate71 { get; set; }
        public string SecondaryProcedure72 { get; set; }
        public string SecondaryProcedureDate72 { get; set; }
        public string SecondaryProcedure73 { get; set; }
        public string SecondaryProcedureDate73 { get; set; }
        public string SecondaryProcedure74 { get; set; }
        public string SecondaryProcedureDate74 { get; set; }
        public string SecondaryProcedure75 { get; set; }
        public string SecondaryProcedureDate75 { get; set; }
        public string SecondaryProcedure76 { get; set; }
        public string SecondaryProcedureDate76 { get; set; }
        public string SecondaryProcedure77 { get; set; }
        public string SecondaryProcedureDate77 { get; set; }
        public string SecondaryProcedure78 { get; set; }
        public string SecondaryProcedureDate78 { get; set; }
        public string SecondaryProcedure79 { get; set; }
        public string SecondaryProcedureDate79 { get; set; }
        public string SecondaryProcedure80 { get; set; }
        public string SecondaryProcedureDate80 { get; set; }
        public string SecondaryProcedure81 { get; set; }
        public string SecondaryProcedureDate81 { get; set; }
        public string SecondaryProcedure82 { get; set; }
        public string SecondaryProcedureDate82 { get; set; }
        public string SecondaryProcedure83 { get; set; }
        public string SecondaryProcedureDate83 { get; set; }
        public string SecondaryProcedure84 { get; set; }
        public string SecondaryProcedureDate84 { get; set; }
        public string SecondaryProcedure85 { get; set; }
        public string SecondaryProcedureDate85 { get; set; }
        public string SecondaryProcedure86 { get; set; }
        public string SecondaryProcedureDate86 { get; set; }
        public string SecondaryProcedure87 { get; set; }
        public string SecondaryProcedureDate87 { get; set; }
        public string SecondaryProcedure88 { get; set; }
        public string SecondaryProcedureDate88 { get; set; }
        public string SecondaryProcedure89 { get; set; }
        public string SecondaryProcedureDate89 { get; set; }
        public string SecondaryProcedure90 { get; set; }
        public string SecondaryProcedureDate90 { get; set; }
        public string SecondaryProcedure91 { get; set; }
        public string SecondaryProcedureDate91 { get; set; }
        public string SecondaryProcedure92 { get; set; }
        public string SecondaryProcedureDate92 { get; set; }
        public string SecondaryProcedure93 { get; set; }
        public string SecondaryProcedureDate93 { get; set; }
        public string SecondaryProcedure94 { get; set; }
        public string SecondaryProcedureDate94 { get; set; }
        public string SecondaryProcedure95 { get; set; }
        public string SecondaryProcedureDate95 { get; set; }
        public string SecondaryProcedure96 { get; set; }
        public string SecondaryProcedureDate96 { get; set; }
        public string SecondaryProcedure97 { get; set; }
        public string SecondaryProcedureDate97 { get; set; }
        public string SecondaryProcedure98 { get; set; }
        public string SecondaryProcedureDate98 { get; set; }
        public string SecondaryProcedure99 { get; set; }
        public string SecondaryProcedureDate99 { get; set; }
    }
}
