//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPIforMySql.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ExtractDefinitions
    {
        [DataMember]
        public int? Id { get; set; }
        [DataMember]
        public int ApplicationId { get; set; }
        [DataMember]
        public long EnterpriseId { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string QueryDefinition { get; set; }
        [DataMember]
        public System.DateTime DateCreated { get; set; }
        [DataMember]
        public System.DateTime DateUpdated { get; set; }
        [DataMember]
        public int CreatedBy { get; set; }
        [DataMember]
        public int UpdatedBy { get; set; }
    }
}
