//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFrameworkToMySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractDefinition
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public long EnterpriseId { get; set; }
        public string Name { get; set; }
        public string QueryDefinition { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
    }
}
