//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClientDB_237006Entities : DbContext
    {
        public ClientDB_237006Entities()
            : base("name=ClientDB_237006Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetInpatientData_Result> GetInpatientData(Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd, string final)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(System.DateTime));
    
            var finalParameter = final != null ?
                new ObjectParameter("Final", final) :
                new ObjectParameter("Final", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInpatientData_Result>("GetInpatientData", dateStartParameter, dateEndParameter, finalParameter);
        }
    
        public virtual ObjectResult<GetOutpatientData_Result> GetOutpatientData(Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd, string final)
        {
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("DateStart", dateStart) :
                new ObjectParameter("DateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(System.DateTime));
    
            var finalParameter = final != null ?
                new ObjectParameter("Final", final) :
                new ObjectParameter("Final", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOutpatientData_Result>("GetOutpatientData", dateStartParameter, dateEndParameter, finalParameter);
        }
    }
}
