using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AWSHubService.Models
{
    public partial class vwOutpatient
    {
            public string EnterpriseName { get; set; }
            public string EnterpriseID { get; set; }
            public string ExportQueueKey { get; set; }
            public string EventTypeKey { get; set; }
            public string RecordType { get; set; }
            public string CodeSetKey { get; set; }
            public string VisitKey { get; set; }
            public string FacilityName { get; set; }
            public string WorkingOrFinal { get; set; }
            public string PatientClassifications3M { get; set; }
            public string PatientType { get; set; }
            public string PatientTypeDescription { get; set; }
            public string VisitType { get; set; }
            public string VisitTypeDescription { get; set; }
            public string PatientLastName { get; set; }
            public string PatientFirstName { get; set; }
            public string PatientMiddleName { get; set; }
            public string PatientAlias { get; set; }
            public string StreetAddress1 { get; set; }
            public string StreetAddress2 { get; set; }
            public string City { get; set; }
            public string State { get; set; }
            public string ZipCode { get; set; }
            public string County { get; set; }
            public string Country { get; set; }
            public string Phone { get; set; }
            public string CellPhone { get; set; }
            public string Fax { get; set; }
            public string Email { get; set; }
            public string BirthDateTime { get; set; }
            public string Sex { get; set; }
            public string MaritalStatus { get; set; }
            public string Race { get; set; }
            public string RaceDescription { get; set; }
            public string Ethnicity { get; set; }
            public string EthnicityDescription { get; set; }
            public string SSN { get; set; }
            public string CitizenshipStatus { get; set; }
            public string MilitaryStatus { get; set; }
            public string DriversLicenseNumber { get; set; }
            public string ProviderId { get; set; }
            public string ProviderNumber { get; set; }
            public string PatientId { get; set; }
            public string MRN { get; set; }
            public string ClaimID { get; set; }
            public string FromDate { get; set; }
            public string TypeOfAdmission { get; set; }
            public string AdmissionTypeDescription { get; set; }
            public string AgeInDays { get; set; }
            public string AgeInYears { get; set; }
            public string IcdVersionQualifier { get; set; }
            public string ReasonForVisitDiagnosis1 { get; set; }
            public string ReasonForVisitDiagnosis2 { get; set; }
            public string ReasonForVisitDiagnosis3 { get; set; }
            public string AdmitDiagnosis { get; set; }
            public string PrincipalDiagnosis { get; set; }
            public string PrincipalDiagnosisPOA { get; set; }
            public string DischargeDate { get; set; }
            public string DischargeStatus { get; set; }
            public string DischargeStatusLocal { get; set; }
            public string PrimaryPayer { get; set; }
            public string SecondaryPayer { get; set; }
            public string TertiaryPayer { get; set; }
            public string FinancialClass { get; set; }
            public string AttendingNPI { get; set; }
            public string AttendingName { get; set; }
            public string AttendingDepartment { get; set; }
            public string OperatingNPI { get; set; }
            public string OperatingName { get; set; }
            public string OperatingDepartment { get; set; }
            public string ReferringNPI { get; set; }
            public string ReferringName { get; set; }
            public string ReferringDepartment { get; set; }
            public string RenderingNPI { get; set; }
            public string RenderingName { get; set; }
            public string RenderingDepartment { get; set; }
            public string GrouperType { get; set; }
            public string GrouperVersion { get; set; }
            public string TotalCharges { get; set; }
            public string TotalNonCharges { get; set; }
            public string TypeOfBill { get; set; }
            public string DeathDate { get; set; }
            public string ConditionCode1 { get; set; }
            public string ConditionCode2 { get; set; }
            public string ConditionCode3 { get; set; }
            public string ConditionCode4 { get; set; }
            public string ConditionCode5 { get; set; }
            public string ConditionCode6 { get; set; }
            public string ConditionCode7 { get; set; }
            public string ConditionCode8 { get; set; }
            public string ConditionCode9 { get; set; }
            public string ConditionCode10 { get; set; }
            public string ConditionCode11 { get; set; }
            public string OccurrenceCode1 { get; set; }
            public string OccurrenceCodeDate1 { get; set; }
            public string OccurrenceCode2 { get; set; }
            public string OccurrenceCodeDate2 { get; set; }
            public string OccurrenceCode3 { get; set; }
            public string OccurrenceCodeDate3 { get; set; }
            public string OccurrenceCode4 { get; set; }
            public string OccurrenceCodeDate4 { get; set; }
            public string OccurrenceCode5 { get; set; }
            public string OccurrenceCodeDate5 { get; set; }
            public string OccurrenceCode6 { get; set; }
            public string OccurrenceCodeDate6 { get; set; }
            public string OccurrenceCode7 { get; set; }
            public string OccurrenceCodeDate7 { get; set; }
            public string OccurrenceCode8 { get; set; }
            public string OccurrenceCodeDate8 { get; set; }
            public string OccurrenceCode9 { get; set; }
            public string OccurrenceCodeDate9 { get; set; }
            public string OccurrenceCode10 { get; set; }
            public string OccurrenceCodeDate10 { get; set; }
            public string ValueCode1 { get; set; }
            public string ValueCodeAmount1 { get; set; }
            public string ValueCode2 { get; set; }
            public string ValueCodeAmount2 { get; set; }
            public string ValueCode3 { get; set; }
            public string ValueCodeAmount3 { get; set; }
            public string ValueCode4 { get; set; }
            public string ValueCodeAmount4 { get; set; }
            public string ValueCode5 { get; set; }
            public string ValueCodeAmount5 { get; set; }
            public string ValueCode6 { get; set; }
            public string ValueCodeAmount6 { get; set; }
            public string ValueCode7 { get; set; }
            public string ValueCodeAmount7 { get; set; }
            public string ValueCode8 { get; set; }
            public string ValueCodeAmount8 { get; set; }
            public string ValueCode9 { get; set; }
            public string ValueCodeAmount9 { get; set; }
            public string ValueCode10 { get; set; }
            public string ValueCodeAmount10 { get; set; }
            public string ValueCode11 { get; set; }
            public string ValueCodeAmount11 { get; set; }
            public string ValueCode12 { get; set; }
            public string ValueCodeAmount12 { get; set; }
            public string SecondaryDiagnosis1 { get; set; }
            public string SecondaryDiagnosisPOA1 { get; set; }
            public string SecondaryDiagnosis2 { get; set; }
            public string SecondaryDiagnosisPOA2 { get; set; }
            public string SecondaryDiagnosis3 { get; set; }
            public string SecondaryDiagnosisPOA3 { get; set; }
            public string SecondaryDiagnosis4 { get; set; }
            public string SecondaryDiagnosisPOA4 { get; set; }
            public string SecondaryDiagnosis5 { get; set; }
            public string SecondaryDiagnosisPOA5 { get; set; }
            public string SecondaryDiagnosis6 { get; set; }
            public string SecondaryDiagnosisPOA6 { get; set; }
            public string SecondaryDiagnosis7 { get; set; }
            public string SecondaryDiagnosisPOA7 { get; set; }
            public string SecondaryDiagnosis8 { get; set; }
            public string SecondaryDiagnosisPOA8 { get; set; }
            public string SecondaryDiagnosis9 { get; set; }
            public string SecondaryDiagnosisPOA9 { get; set; }
            public string SecondaryDiagnosis10 { get; set; }
            public string SecondaryDiagnosisPOA10 { get; set; }
            public string SecondaryDiagnosis11 { get; set; }
            public string SecondaryDiagnosisPOA11 { get; set; }
            public string SecondaryDiagnosis12 { get; set; }
            public string SecondaryDiagnosisPOA12 { get; set; }
            public string SecondaryDiagnosis13 { get; set; }
            public string SecondaryDiagnosisPOA13 { get; set; }
            public string SecondaryDiagnosis14 { get; set; }
            public string SecondaryDiagnosisPOA14 { get; set; }
            public string SecondaryDiagnosis15 { get; set; }
            public string SecondaryDiagnosisPOA15 { get; set; }
            public string SecondaryDiagnosis16 { get; set; }
            public string SecondaryDiagnosisPOA16 { get; set; }
            public string SecondaryDiagnosis17 { get; set; }
            public string SecondaryDiagnosisPOA17 { get; set; }
            public string SecondaryDiagnosis18 { get; set; }
            public string SecondaryDiagnosisPOA18 { get; set; }
            public string SecondaryDiagnosis19 { get; set; }
            public string SecondaryDiagnosisPOA19 { get; set; }
            public string SecondaryDiagnosis20 { get; set; }
            public string SecondaryDiagnosisPOA20 { get; set; }
            public string SecondaryDiagnosis21 { get; set; }
            public string SecondaryDiagnosisPOA21 { get; set; }
            public string SecondaryDiagnosis22 { get; set; }
            public string SecondaryDiagnosisPOA22 { get; set; }
            public string SecondaryDiagnosis23 { get; set; }
            public string SecondaryDiagnosisPOA23 { get; set; }
            public ICollection<vwOutpatientDetails> OutpatientDetails { get; set; }
    }
}
